services:
  postgres:
    image: postgres:17-alpine
    container_name: nextjs-auth-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: salla
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - nextjs-auth-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.50"

volumes:
  postgres_data:

networks:
  nextjs-auth-network:
    driver: bridge
